# Copyright (c) 2026, NuDanOS. All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#
# TACACS+ login on NuDanOS. Debian 13's sssd has no TACACS+ provider, so
# login uses pam_tacplus (authentication, authorization) and nss_tacplus
# (user lookup, mapping a TACACS+ user to the local account tacacsN of its
# privilege level). Both read servers and secrets from one root-only file.

package Vyatta::Login::TacplusLogin;

use strict;
use warnings;

use Exporter qw(import);
use File::Temp qw(tempfile);
use File::Basename qw(dirname);

our @EXPORT_OK =
  qw(servers_file_content level_groups write_private_file mapped_account_command);

# servers_file_content(\@servers, $timeout): the include= file pam_tacplus
# and nss_tacplus read. Each secret precedes its server, so it applies to
# that server in both. @servers holds { address, port, secret }.
sub servers_file_content {
    my ( $servers, $timeout ) = @_;
    return '' unless @$servers;
    my $out = "# TACACS+ servers for login (pam_tacplus, nss_tacplus)\n"
      . "# automatically generated by vyatta-tacacs, do not edit\n";
    for my $s (@$servers) {
        my $addr = $s->{address} =~ /:/ ? "[$s->{address}]" : $s->{address};
        $out .= "secret=$s->{secret}\nserver=$addr:$s->{port}\n";
    }
    $out .= "timeout=$timeout\n" if defined $timeout;
    return $out;
}

# level_groups($level, $file): the groups of a DANOS login level, from
# lines "level:group1,group2" (/opt/vyatta/etc/level).
sub level_groups {
    my ( $level, $file ) = @_;
    open my $fh, '<', $file or return ();
    while ( my $line = <$fh> ) {
        chomp $line;
        my ( $name, $groups ) = split /:/, $line, 2;
        next unless defined $groups && $name eq $level;
        close $fh;
        return grep { length } split /,/, $groups;
    }
    close $fh;
    return ();
}

# mapped_account_command($level, $shell): the command that creates the
# mapped account tacacs$level, as libtacplus-map1's postinst creates it:
# uid 1000 or above, since nss_tacplus maps a uid back to its TACACS+ user
# only from min_uid (1001) up.
sub mapped_account_command {
    my ( $level, $shell ) = @_;
    return ( 'adduser', '--quiet', '--firstuid', '1000', '--disabled-login',
        '--ingroup', 'tacacs', '--shell', $shell,
        '--gecos', "TACACS+ mapped user at privilege level $level",
        "tacacs$level" );
}

# write_private_file($path, $content): replace $path atomically, readable
# by root only (it holds shared secrets).
sub write_private_file {
    my ( $path, $content ) = @_;
    my ( $fh, $tmp ) = tempfile( '.tacplus-XXXXXX', DIR => dirname($path) );
    chmod 0600, $tmp or die "chmod $tmp: $!";
    print $fh $content or die "write $tmp: $!";
    close $fh or die "close $tmp: $!";
    rename $tmp, $path or die "rename $tmp to $path: $!";
    return;
}

1;
